package com.codingstudio.mutualtransfer.model.online_payment

data class OnlinePayment (
    var online_payment_id: String? = null,
    var fk_user_id: String? = null,
    var payment_date: String? = null,
    var payment_mode: String? = null,
    var payment_status: String? = null,
    var amount_refunded: String? = null,
    var refund_status: String? = null,
    var captured: String? = null,
    var card_id: String? = null,
    var bank: String? = null,
    var wallet: String? = null,
    var vpa: String? = null,
    var fee: String? = null,
    var tax: String? = null,
    var order_id: String? = null,
    var entity: String? = null,
    var coins: String? = null,
    var amount: String? = null,
    var amount_paid: String? = null,
    var amount_due: String? = null,
    var currency: String? = null,
    var receipt: String? = null,
    var offer_id: String? = null,
    var status: String? = null,
    var attempts: String? = null,
    var notes: String? = null,
    var order_created_at: String? = null,
    var razorpay_payment_id: String? = null,
    var razorpay_signature: String? = null,
    var error_code: String? = null,
    var error_description: String? = null,
    var error_source: String? = null,
    var error_step: String? = null,
    var error_reason: String? = null,
    var error_field: String? = null,
    var created_at: String? = null,
    var updated_at: String? = null
)